### ISSUE TITLE
Add "public campaign financing received" to backend

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#100]
Suzanne will input this into the spreadsheet manually and then we'll expose it as data that the frontend can use.

The number should be `null` if the candidate is not eligible for public funding (i.e. Mayoral candidates,  citywide offices, or OUSD), or a number greater than or equal to zero if they are eligible.

**Comment by adborden** [comment]
I think we can skip the back end and just add it to the front end.

Sort of related, I thought we could get away with only keeping track of a candidates mates finance info, but when a candidate is in multiple election years the finance data will show up wrong in at least one place. I need to rethink the model on the front end. How are we modeling it on the back end? 


For example, if the "received public financing" is different in 2018 than 2016, how are we tracking that?

**Comment by sfdoran** [comment]
Why not have a candidate file for each election? For example, nancy-sidebotham.2016.md and nancy-sidebotham.2018.md? In the spreadsheet the candidates in more than one election will have a separate record for each election since the committee will have a different name, maybe a different filer ID, could be a different office, etc.

If you want me to add the 2016 public financing to the 2016 candidate files let me know, otherwise I'll enter it in the spreadsheets today.

**Comment by adborden** [comment]
Yeah, I think we have to do it that way, but then we end up with
elections that are completely siloed from each other. In reality,
you would want to see some things things like candidates and committees
across elections.

Starting siloed is probably the right place to start and we can
figure out how to show a candidate page that shows all the elections
they have participated in later.

@sfdoran if you can add it to the existing candidate files, that would
be preferred.

Quoting Suzanne Doran (2018-06-13 09:21:40)
> Why not have a candidate file for each election? For example, nancy-sidebotham.2016.md and nancy-sidebotham.2018.md? In the spreadsheet the candidates in more than one election will have a separate record for each election since the committee will have a different name, maybe a different filer ID, could be a different office, etc.
> 
> If you want me to add the 2016 public financing to the 2016 candidate files let me know, otherwise I'll enter it in the spreadsheets today.
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/caciviclab/disclosure-backend-static/issues/100#issuecomment-396999461

--
Aaron D Borden
Human and hacker
