### ISSUE TITLE
There should be data for 2018 June Measure D

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#101]
There is a committee in support of the ballot measure now, as well as a major donor that is supporting the measure.

Let's make sure that that is represented on Open Disclosure ASAP.

Primary:
Protect Oakland Libraries - 1400467

Major Donor:
Friends of the Oakland Public Library - Pending

**Comment by tdooner** [comment]
@sfdoran It appears as though Friends of the Oakland Public Library has not filed anything yet. Does that sound right?

**Comment by sfdoran** [comment]
No they filed a 497.

On May 10, 2018, at 9:25 PM, Tom Dooner <notifications@github.com<mailto:notifications@github.com>> wrote:


@sfdoran<https://github.com/sfdoran> It appears as though Friends of the Oakland Public Library has not filed anything yet. Does that sound right?

**Comment by sfdoran** [comment]
1/24/18 for $29,000

**Comment by adborden** [comment]
@tdooner I think this is resolved? I've got a PR on the front end that shows the measure D data, so it must be coming through, no? https://github.com/caciviclab/odca-jekyll/pull/84

**Comment by tdooner** [comment]
Great!
