### ISSUE TITLE
How to handle empty Sup_Opp_Cd?

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#108]
There are a number of contributions, many including significant totals, with empty `Sup_Opp_Cd`.

For instance, the below row is a $150,000 contribution presumably in support of the not-yet-official "Oakland Children's Initiative" but the `Sup_Opp_Cd` column is empty. Are we to assume this contribution is in support of the ballot measure?

```
downloads/csv/efile_COAK_2018_497.csv
9:1400908,East Bay Community Foundation (nonprofit 501(c)(3)),000,RCP,2018-05-29,,,,S497,F497P2,EXP14,COM,The Oakland Fund,"","","","","",Oak
land,CA,94607,"","","",,2018-05-25,,150000.00,1310647,"","","","","","","","","","",Oakland Children's Initiative,"",City of Oakland,"","",25
400
```

Why is it even possible to leave this field blank when filling out the form? @sfdoran - As for this data cleanup, how do you handle it? Is this one of those "I'd ideally ask them to amend their filing" kind of situations?

**Comment by sfdoran** [comment]
If you look at the Form 497, you'll see that when a contribution is reported the payor has to list the date the contribution is made, name and address of the recipient, a candidate or ballot measure, amount and election date. A support/oppose item isn't included the way it is on the 496 or the 460 Schedule D, and you'll see the Sup_Opp_Cd column isn't included in the 497 table.

To determine what the contribution is supporting/opposing you have to look at who/what that recipient committee supports/opposes. That info is on the committee's 410 and also the name of the committee.

When we get a Form 410 and set up a filer account, we manually associate the election and candidate or ballot measure the committee supports or opposes with the committee. NetFile doesn't provide a way for us to export that data, unfortunately. 

For now I think this is an item we need to enter manually, e.g. for the Oakland 2018 election The Oakland Fund supports the Oakland Children's initiative so any contribution to the Oakland Fund is a contribution supporting the Oakland Children's Initiative.

![image](https://user-images.githubusercontent.com/19939684/41628636-4ca3f186-73da-11e8-8efc-32d288acb47c.png)

**Comment by mikeubell** [comment]
@tdooner @sfdoran I think this has been fixed by the Ballot Measure and Support Or Oppose columns in the committees sheet.
