### ISSUE TITLE
Is there a way we can get Form 410 from Netfile?

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#109]
Maybe with the swagger API? This would be really useful to be able to match up committee names with whether they support or oppose ballot measures.

I think many 410's are scans of paper, so I'm guessing the answer is no.

**Comment by sfdoran** [comment]
410s can be submitted on paper or they can be e-filed. When the filer updates their committee info, it is updated in the cover page info on their next campaign statement, but there's no indication of the effective date. You have to look at the PDF of the 410 filing.

**Comment by adborden** [comment]
Is this something we could ask Netfile for? Sounds like when it's filed, they _could_ update it then, but wait for the next statement instead.

**Comment by sfdoran** [comment]
Explain more what we’d be asking for so I understand. Currently e-filed 410s arent published as data. We’d be asking for an additional table of data - the way 497 & 496 data are separate from the 460 data. It’s a good idea - it could eliminate the need to gather a lot of info manually. Another way that I’m trying is asking for full access to the data we (staff) input about the committees into the filing admin system.

**Comment by tdooner** [comment]
@sfdoran To expand a bit on my earlier questions,

1) What happens to the 410 data when it is received? Is it digitized into Netfile?
2) If so, then maybe Netfile can publish the 410 data in a similar format to how it publishes 460 and such.
3) Also, perhaps it should be required to e-file 410 forms in Oakland.

This is pretty low priority, I just wanted to create this issue to create a backlog of Netfile "nice-to-have"s for next time they come asking.

**Comment by sfdoran** [comment]
1. The City of Oakland doesn't require e-filing for 410s. Once a candidate registers their committee (i.e. files an initial 410), they can e-file amendments to their 410 using NetFile. The filer inputs the info required on the 410 into their NetFile account, that is how it gets entered on their 460 and amended 410s. However, if they paper-file a 410 and do not update that info in their NetFile account, the updates will not be reflected in the data. That is why you see records without filer ids or with different committee names than what is on their latest 410. On the administrator side, when we receive a 410, paper or e-file, we have to enter the updates manually into the account for that filer (different from their user account). 

2, Yes, we can ask them to publish that data and I have asked them about it already.

3. I agree in general, but currently the committee doesn't have an account to e-file with until they file the initial 410 on paper.
