### ISSUE TITLE
What's up with Lori Droste?

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#118]
She has negative loans received, and so we report:

```
"contributions_by_origin": {
  "Within California": 3883.1
},
```
but then we also report
```
"total_contributions": 0
```

**Comment by adborden** [comment]
@sfdoran currently, the front end looks at `total_contributions` and `total_expenditures` to determine if there is any finance data avaible. In Lori's case, since there are only negative loans, we show the "no finance data available" messaging.

**Comment by sfdoran** [comment]
First thought -- 0.00 contributions or 0.00 expenditures is different than "no finance data available." To me "no finance data available" means no campaign statements filed. Is there a way to only show that message if the value is null?

What happened with Lori is $ got moved from one accounting category to another (loans received v. monetary contributions) within the same part of the balance sheet (revenue). So there wasn't a net change in contributions received.

The original loan was for the 2014 campaign, but the debt was forgiven in 2017 so it appears as an itemized contribution in 2017, even though the net change to contributions received is 0.00.

@tdooner how do we distinguish contributions and/or expenditures for different elections when the candidate committees has the same filer ID for multiple elections?

**Comment by mikeubell** [comment]
I can't find the candidate.  Was this for an old or non-Oakland election?  Should we close this?

**Comment by sfdoran** [comment]
Yes, she's a berkeley council member and it's an old election. I'd close it.
