### ISSUE TITLE
Group ballot measure money supporting/opposing by origin (Oakland/California/out of state)

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#12]

**Comment by mikeubell** [comment]
I think we should group by the locale of contributors to committees.  If there is an IEC that works on multiple ballot measures then we could proportion the money in proportion to what is spent.  This latter may be tricky.

**Comment by mikeubell** [comment]
We need to do something to import 410 information from the state.

**Comment by mikeubell** [comment]
Don't need 410s.
