### ISSUE TITLE
Data inaccuracies circa July 9

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#125]
From Suzanne: A lot of data matches but there are three discrepancies:

Desley Brooks: We should exclude contributions and expenditures prior to 2/6/2017 for her. That's when her 2018 campaign started. She reported 0.00 activity for 1/1/2017-6/30/2017 so that should be easy.  Correct numbers: Total contributions $24,900, Loans $100, Total Expenditures $5951.

Jody London: My total expenditures are $110 under OD.

Rosie Torres: My total contributions are under OD by $3140 & my total expenditures are under OD by  $3279.

Suzanne is going to double-check IE's. We should also try to figure out where the discrepancies come from.

**Comment by tdooner** [comment]
For ballot measures: LL is a good example. The "Committee_Type" on the Summary sheet is often wrong. For example Filer ID `1387983` is actually a BMC and shouldn't be excluded in the referendum supporters calculator.

**Comment by tdooner** [comment]
Also for instance Dan Kalb, a candidate with independent expenditures in support/opposition (https://caciviclab.org/odca-jekyll/candidate/oakland/2016-11-08/dan-kalb/)

We need to exclude `Expn_Code` = MON and IKD (only IND) because they go to the candidate committee and are counted as contributions already. IND means independent expenditures. (In which case the `Payee_NamL` field is junk because it's an independent expenditure).

**Comment by tdooner** [comment]
Also, data for LL has disappeared.

**Comment by tdooner** [comment]
London Breed's page is wrong (she has no FPPC ID in the spreadsheet)

**Comment by tdooner** [comment]
There were independent expenditures against JJ and KK that are not reflected on the site. From East Bay Rental Association.

**Comment by mikeubell** [comment]
If there is still an issue here, we can reopen.
