### ISSUE TITLE
Expenditures supporting/opposing candidate should only include Independent Expenditures

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/disclosure-backend-static#126]
Only expenditures from Schedule D  where type of payment is independent expenditure or Form 496 should be included.

**Comment by sfdoran** [comment]
These are the independent expenditures that should show:

![image](https://user-images.githubusercontent.com/19939684/42704666-9e34ac44-8685-11e8-84cc-c53f6a7d76ee.png)

**Comment by tdooner** [comment]
Hey @sfdoran can you let me know if you get $99,288.96 for Huber Trenado from Families and Educators when you look into it again? I removed non-IND from him and that's what I got.

**Comment by sfdoran** [comment]
@tdooner We agree on Trenado! There is a NetFile bug when I download the data. It is including transactions from amended filings for December (but weirdly not other periods) when they are supposed to be filtered out.

[TRENADO 7.20.18.xlsx](https://github.com/caciviclab/disclosure-backend-static/files/2214993/TRENADO.7.20.18.xlsx)

[TRENADO 7.20.18.txt](https://github.com/caciviclab/disclosure-backend-static/files/2214992/TRENADO.7.20.18.txt)

**Comment by sfdoran** [comment]
@tdooner after I made the same correction for Families and Educators, the total IEs matched the year-to-date totals on the statement. I didn't find any other committee that had transactions from amended filings.

[IE BY CANDIDATE AND MEASURE.xlsx](https://github.com/caciviclab/disclosure-backend-static/files/2215190/IE.BY.CANDIDATE.AND.MEASURE.xlsx)

**Comment by sfdoran** [comment]
I only included Expn_Code = IND and ballot measures where the jurisdiction was a variation of Oakland

**Comment by sfdoran** [comment]
@tdooner One thing that is bugging me - Families and Educators filed 3 496's for IEs in September and October supporting Measure G1 totaling $9,928. That total was showing up on the G1 page. But the subsequent 460's filed by Families and Educators does not include those IEs and they are not in the Schedule D transactions data. So if we only add in 496's with dates later than the most recent 460, why are those 496s included on the G1 page?
