### ISSUE TITLE
Add a start date for contributions to exclude previous elections

### ISSUE THREAD

**Issue by mikeubell** [caciviclab/disclosure-backend-static#134]
For committees that get reused for multiple elections we need to add a start date to the spreadsheet and exclude contributions before then.  Also use 460 previous balance at that date as carry over funds.

**Comment by sfdoran** [comment]
Just echoing Mike here - Desley's page shows how the current method distorts the picture:

According to OD, Desley has raised more for this election than she has be has less in her war chest than she really does. 

Compare her cash balance on the latest statement to OD, it's more than twice as much:

![image](https://user-images.githubusercontent.com/19939684/43745883-f9df90f4-9995-11e8-8966-77f1925ed096.png)
