### ISSUE TITLE
IE from 6/5/18 being counted toward 11/6/18 campaign for Pamela Price

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/disclosure-backend-static#144]
This IE was opposing the Price campaign for County DA.

![image](https://user-images.githubusercontent.com/19939684/44544705-d3634080-a6c7-11e8-9336-f76ba33358d4.png)

**Comment by sfdoran** [comment]
I think it is because you find the IE's by the candidate name listed by the committee making the expenditure without differentiating between election dates or jurisdiction. If if was the candidate name plus the jurisdiction or election date that would filter this one out. Right now the spreadsheet has oakland-2018 for county and regional measures. Maybe we need to change that in the spreadsheet?

**Comment by mikeubell** [comment]
So this could be a different case I guess.

**Comment by mikeubell** [comment]
I think this is solved with #134 by only considering transactions after a certain date.

**Comment by sfdoran** [comment]
Folks are sloppy is true! Also the system is lame! There could be standardized codes for jurisdiction but like so many other instances the filers are allowed to improvise.

If dates don't solve the problem, could you try assigning jurisdiction Oakland if it contains a variation of "Oakland"?

**Comment by adborden** [comment]
@sfdoran @mikeubell did #134 fix the issue?

**Comment by sfdoran** [comment]
Yes.
