### ISSUE TITLE
"totals" endpoints should not be Oakland-specific, and include ballot measures

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#150]
The homepage figure (currently titled "Funds Raised In Oakland") is kind of weird - it only includes contributions to Oakland candidates from within Oakland. For a single metric that encompasses the entire election, I was expecting the figure to include pretty much all activity in the election, including:

* contributions to Oakland candidates from outside Oakland
* contributions to Ballot Measures on the Oakland ballot

@sfdoran is going to come up with a new title for the figure that represents it.

Was there a rationale for choosing the existing number?

**Comment by sfdoran** [comment]
@tdooner How is this? "Contributions flowing into Oakland's 2018 Election"

**Comment by adborden** [comment]
@tanyastropheus is picking this up!

**Comment by sfdoran** [comment]
@adborden @tdooner I thought this was done - we've already changed the heading. Can we get it done by  Monday so the figure reflects the new heading when we issue our press release on Tuesday?

**Comment by adborden** [comment]
@sfdoran oh you're right. Let me create another issue for Tanya's work.

**Comment by adborden** [comment]
Opened https://github.com/caciviclab/disclosure-backend-static/issues/159 instead
