### ISSUE TITLE
Filing ID# 174032415 is listed on Netfile as a 460 but it's actually a 470

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#167]
See: https://netfile.com/Connect2/api/public/image/174032415

Netfile API returns it as a 460. Is this something you can change from the admin side of things, @sfdoran ?

**Comment by sfdoran** [comment]
Yes, it was initially uploaded as a 460 by accident, but has since been corrected on our end. When paper filings come in, we assign the form type.
