### ISSUE TITLE
possible filer error

### ISSUE THREAD

**Issue by ckingbailey** [caciviclab/disclosure-backend-static#177]
"OAKLANDERS FOR RESPONSIBLE LEADERSHIP, OPPOSING DESLEY BROOKS FOR OAKLAND CITY COUNCIL 2018", filer id 1410279, shows up under both [the supporting](https://github.com/caciviclab/disclosure-backend-static/blob/master/build/_data/candidates/oakland/2018-11-06/desley-brooks.json#L36) and opposing committee list for Brooks.

[I am told](https://github.com/caciviclab/disclosure-backend-static/issues/176#issuecomment-429848570) this is because they misfiled $171.61 in support of the candidate.

**Comment by adborden** [comment]
@sfdoran is this still an issue?

**Comment by ckingbailey** [comment]
Closed while reviewing issues for 2020 release
