### ISSUE TITLE
Add to API the winner of each election

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#182]
This should come from the `is_winner` column in the [spreadsheet](https://docs.google.com/spreadsheets/d/1vJR8GR5Bk3bUQXziPiQe7to1O-QEm-_5GfD7hPjp-Xc/edit#gid=0).

**Comment by adborden** [comment]
Only a tiny bit of ruby required :)

**Comment by adborden** [comment]
This was added to the API in https://github.com/caciviclab/disclosure-backend-static/pull/184.

The front end issue is still open https://github.com/caciviclab/odca-jekyll/issues/287
