### ISSUE TITLE
Update to Ruby 2.6

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend-static#192]
Ruby 2.3 is [already end of life](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/), not receiving security updates. Folks have also had issues with bundler versions, 2.0 is commonly installed but the Gemfile.lock specifies 1.16.3

**Comment by tdooner** [comment]
we're on 2.7 now!
