### ISSUE TITLE
make import issue?

### ISSUE THREAD

**Issue by rkiddy** [caciviclab/disclosure-backend-static#193]
I was able to get up to "make import" with no problems. I had to install Mac dev tools on this mac. I already had ruby on it. I had to install postgres but that went fine.

When I tried to do a "make import", I got the errors below.

I have logs of all the other installs I did in this session and can attach them also, if they are of interest.

     $ make import
     dropdb disclosure-backend || true
     dropdb: database removal failed: ERROR:  database "disclosure-backend" does not exist
     createdb disclosure-backend
     echo 'DROP TABLE IF EXISTS candidates;' | psql disclosure-backend
     NOTICE:  table "candidates" does not exist, skipping
     DROP TABLE
     csvsql --doublequote --db postgresql:///disclosure-backend --insert downloads/csv/candidates.csv
     echo 'ALTER TABLE "candidates" ADD COLUMN id SERIAL PRIMARY KEY;' | psql disclosure-backend
     ALTER TABLE
     echo 'DROP TABLE IF EXISTS referendums;' | psql disclosure-backend
     NOTICE:  table "referendums" does not exist, skipping
     DROP TABLE
     csvsql --doublequote --db postgresql:///disclosure-backend --insert downloads/csv/referendums.csv
     echo 'ALTER TABLE "referendums" ADD COLUMN id SERIAL PRIMARY KEY;' | psql disclosure-backend
     ALTER TABLE
     echo 'DROP TABLE IF EXISTS name_to_number;' | psql disclosure-backend
     NOTICE:  table "name_to_number" does not exist, skipping
     DROP TABLE
     csvsql --doublequote --db postgresql:///disclosure-backend --insert downloads/csv/name_to_number.csv
     echo 'DROP TABLE IF EXISTS committees;' | psql disclosure-backend
     NOTICE:  table "committees" does not exist, skipping
     DROP TABLE
     csvsql --doublequote --db postgresql:///disclosure-backend --insert downloads/csv/committees.csv
     echo 'ALTER TABLE "committees" ADD COLUMN id SERIAL PRIMARY KEY;' | psql disclosure-backend
     ALTER TABLE
     echo 'DROP TABLE IF EXISTS office_elections;' | psql disclosure-backend
     NOTICE:  table "office_elections" does not exist, skipping
     DROP TABLE
     csvsql --doublequote --db postgresql:///disclosure-backend --insert downloads/csv/office_elections.csv
     echo 'ALTER TABLE "office_elections" ALTER COLUMN title TYPE varchar(50);' | psql disclosure-backend
     ALTER TABLE
     echo 'ALTER TABLE "office_elections" ADD COLUMN id SERIAL PRIMARY KEY;' | psql disclosure-backend
     ALTER TABLE
     echo 'DROP TABLE IF EXISTS elections;' | psql disclosure-backend
     NOTICE:  table "elections" does not exist, skipping
     DROP TABLE
     csvsql --doublequote --db postgresql:///disclosure-backend --insert downloads/csv/elections.csv
     echo 'ALTER TABLE "elections" ADD COLUMN id SERIAL PRIMARY KEY;' | psql disclosure-backend
     ALTER TABLE
     DATABASE_NAME=disclosure-backend ./bin/import-file downloads/csv 496
       Removing empty Tran_Date...   Removing amended filings... DELETE 0
     DATABASE_NAME=disclosure-backend ./bin/import-file downloads/csv 497
       Removing empty Tran_Date...   Removing amended filings... DELETE 0
     DATABASE_NAME=disclosure-backend ./bin/import-file downloads/csv A-Contributions
       Removing empty Tran_Date... DELETE 2
       Removing amended filings... DELETE 44187
     DATABASE_NAME=disclosure-backend ./bin/import-file downloads/csv B1-Loans
       Removing empty Tran_Date...   Removing amended filings... DELETE 234
     DATABASE_NAME=disclosure-backend ./bin/import-file downloads/csv B2-Loans
       Removing empty Tran_Date...   Removing amended filings... DELETE 0
     DATABASE_NAME=disclosure-backend ./bin/import-file downloads/csv C-Contributions
       Removing empty Tran_Date... DELETE 0
       Removing amended filings... DELETE 433
     DATABASE_NAME=disclosure-backend ./bin/import-file downloads/csv D-Expenditure
       Removing empty Tran_Date...   Removing amended filings... DELETE 867
     DATABASE_NAME=disclosure-backend ./bin/import-file downloads/csv E-Expenditure
       Removing empty Tran_Date...   Removing amended filings... DELETE 15753
     DATABASE_NAME=disclosure-backend ./bin/import-file downloads/csv F-Expenses
       Removing empty Tran_Date...   Removing amended filings... DELETE 2871
     DATABASE_NAME=disclosure-backend ./bin/import-file downloads/csv F461P5-Expenditure
       Removing empty Tran_Date...   Removing amended filings... DELETE 285
     DATABASE_NAME=disclosure-backend ./bin/import-file downloads/csv F465P3-Expenditure
       Removing empty Tran_Date...   Removing amended filings... DELETE 94
     DATABASE_NAME=disclosure-backend ./bin/import-file downloads/csv F496P3-Contributions
       Removing empty Tran_Date... DELETE 0
       Removing amended filings... DELETE 0
     DATABASE_NAME=disclosure-backend ./bin/import-file downloads/csv G-Expenditure
       Removing empty Tran_Date...   Removing amended filings... DELETE 5139
     DATABASE_NAME=disclosure-backend ./bin/import-file downloads/csv H-Loans
       Removing empty Tran_Date...   Removing amended filings... DELETE 5
     DATABASE_NAME=disclosure-backend ./bin/import-file downloads/csv I-Contributions
       Removing empty Tran_Date... DELETE 0
       Removing amended filings... DELETE 186
     DATABASE_NAME=disclosure-backend ./bin/import-file downloads/csv Summary
       Removing empty Tran_Date...   Removing amended filings... DELETE 24696
     echo 'CREATE TABLE "calculations" (id SERIAL PRIMARY KEY, subject_id integer, subject_type varchar(30), name varchar(40), value jsonb);' | psql disclosure-backend
     CREATE TABLE
     ./bin/remove_duplicate_transactions
     DELETE 9
     DELETE 71
     ./bin/make_view
     NOTICE:  view "Measure_Expenditures" does not exist, skipping
     DROP VIEW
     CREATE VIEW
     NOTICE:  view "combined_contributions" does not exist, skipping
     DROP VIEW
     NOTICE:  view "candidate_contributions" does not exist, skipping
     DROP VIEW
     NOTICE:  view "measure_contributions" does not exist, skipping
     DROP VIEW
     NOTICE:  view "all_contributions" does not exist, skipping
     DROP VIEW
     CREATE VIEW
     ERROR:  column "FPPC" does not exist
     LINE 7:   ON "FPPC"::varchar = all_contributions."Filer_ID"
                  ^
     CREATE VIEW
     ERROR:  relation "candidate_contributions" does not exist
     LINE 2:   SELECT * from candidate_contributions
                             ^
     NOTICE:  view "independent_candidate_expenditures" does not exist, skipping
     DROP VIEW
     ERROR:  column "Candidate" does not exist
     LINE 13: ...M(CONCAT("Cand_NamF", ' ', "Cand_NamL"))) = LOWER("Candidate...
                                                                   ^
     bash-3.2$ 
     bash-3.2$ 
     bash-3.2$ exit
     exit
     
     Script done on Fri May 10 09:40:38 2019

**Comment by mikeubell** [comment]
I'm cleaning up old issues.  Is this still a problem?  Sorry for not responding sooner. No one else has reported an issue here.  Perhaps it is a tool version problem?  I will close if you are still having the problem you can reopen.
