### ISSUE TITLE
Endpoint for candidate contributions

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend-static#20]
Not sure where this stacks up in priorities or difficulty. Looking for an endpoint to get the contributions made to a specific candidate. Maybe `/candidate/:id/contributions/:type` with some kind of `limit` and `offset` parameter so we can scroll the dataset. And maybe we can break this down a bit, since it's kind of 3 datasets.

Here's what the frontend mock is asking for:
!['sm-mobile-6-candidate-contributions'](https://cloud.githubusercontent.com/assets/6467815/18463172/05c7e144-793d-11e6-9224-8c9dcfafd27c.png)

**Comment by adborden** [comment]
Thinking about implementation for a static backend, we could hard-code a limit (page size) and then just dump those page-size junks into json files. Then the query parameters just become `page` number and we fetch the chunk based on that. Directory would look like this, each index.json with up to page-size number of contributors within:

```
candidate/
└── 1
    └── contributions
        ├── committee
        │   ├── 1
        │   │   └── index.json
        │   ├── 2
        │   │   └── index.json
        │   └── 3
        │       └── index.json
        ├── individual
        │   ├── 1
        │   │   └── index.json
        │   ├── 2
        │   │   └── index.json
        │   └── 3
        │       └── index.json
        └── other
            ├── 1
            │   └── index.json
            ├── 2
            │   └── index.json
            └── 3
                └── index.json
```

**Comment by tdooner** [comment]
Sorting adds an additional layer of complexity to this which probably breaks your pagination implementation proposal.

I'm thinking that we should just ship all transactions for each type at once instead of attempting pagination/sorting, and let the frontend do all the hard stuff*. After all, right now our entire data set is 1,447 transactions -- not exactly a browser-crashing amount. Sure, it will grow, but we have [in previous incarnations shipped quite a lot of JSON succesfully][1].

\* of course this is my backend-biased viewpoint ;)

[1]: http://www.opendisclosure.io/api/contributions/candidate/2052

**Comment by adborden** [comment]
:+1: I should have looked at the data before saying something :)

Sure, this actually frees us up to do some cool stuff on the frontend.

**Comment by elinaru** [comment]
Groupings are derived the forms, and they are:
- Individual
- Other (includes businesses)
- Not Itemized (all contributions under $100)
- Committee
- Self-Funded (since this is one that requires extra work, my understanding is that we likely won't manage it for the 2016 election.)

**Comment by tdooner** [comment]
Up to you. I was thinking since all four are necessary to render the page that we may as well return them all at once. But if it becomes cumbersome, we could of course split it up by type.

**Comment by adborden** [comment]
Do the groups overlap?Just for back of the envelope calculation, 1447 contributions / 5 groups is about 289 contributions per group. 5 tables with 289 rows is seems pretty busy for one page. It's alot of space to expand/contract for a see more/less toggle.

Can I pitch an alternative, @elinaru? We pick a reasonable sort for the 5-row summary and have "see all" link would take you to a separate table page where you would have more table controls and view a single table with all the data for that group. We could even have a drop down that changes the group, so you don't need to change the page to see the other groups.

I think either way, dumping the whole dataset in a single endpoint is a good first step.

**Comment by adborden** [comment]
@sfdoran pointed out that the calculation for contributors to a committee should be the same, no matter what kind of committee (candidate or otherwise), so this work get's us close to both the contributors for canidate UI component and contributors to committee UI component.

**Comment by adborden** [comment]
Spreadsheet was updated and candidate committees are appearing in the endpoint.
