### ISSUE TITLE
Existing 2020 finance data is not showing up on site

### ISSUE THREAD

**Issue by ckingbailey** [caciviclab/disclosure-backend-static#205]
For example, the "Yes on Q" committee, #1423153, exists, Suzanne has contribution data for it, but that data is not showing up in the built data. Is there something more that needs to be done, on the spreadsheet, for example, to connect the committee to the contributions data for that committee?

**Comment by ckingbailey** [comment]
It appears we may not have been pulling 2020 data because dates only up to 2018 were hard-coded into the Ruby code

**Comment by ckingbailey** [comment]
A bunch of new data came in following Friday 1/31/20 deadline. Some (all?) data is not showing up on site. For example, according to the filing [tweeted here](https://twitter.com/DarwinBondGraha/status/1223644279383289857?s=20), [Stephanie Dominguez Walton, District 1](https://www.opendisclosure.io/candidate/oakland/2020-11-03/stephanie-dominguez-walton/) has received 10x more contributions than what is shown on her page. In that tweet about new filings you can see that [Dan Kalb, District 1](https://www.opendisclosure.io/candidate/oakland/2020-11-03/dan-kalb/) has also received some contributions that are not showing up.
I think this is because the spreadsheet date ranges are not up-to-date.

**Comment by tdooner** [comment]
@ckingbailey I was wondering this too. It must have just been a consequence of the build times. No builds failed or anything. I forced a run of the circle-ci run (odca-jekyll) and the data came through now.

**Comment by ckingbailey** [comment]
Could this have something to do with it? https://travis-ci.org/caciviclab/disclosure-backend-static/builds/645235881
![Screen Shot 2020-02-04 at 11.26.26 AM.png](https://images.zenhubusercontent.com/5c9031c88dcdbd6b61379151/9393274d-4905-4269-bf1c-59d7b9f45647)

I'm wondering if the latest frontend build was relying on old data because the most recent backend build had failed.

**Comment by sfdoran** [comment]
We also have a committee opposing Measure Q - Oakland Neighbors United, No On Measure Q, 1424633 that's been in the ballot measure committee sheet but isn't showing up on the Measure Q page. 

They don't have any campaign finance data yet, but shouldn't the committee show up anyway?

**Comment by ckingbailey** [comment]
This appears to be resolved.

Measure Q on opendisclosure.io
<img src="https://images.zenhubusercontent.com/5c9031c88dcdbd6b61379151/83f03883-142d-41f2-8eff-9def5dc16f3b" width="500">
