### ISSUE TITLE
Add two new calculations for new landing page design

### ISSUE THREAD

**Issue by ckingbailey** [caciviclab/disclosure-backend-static#206]
1. Percentage of contributions from Oakland residents
2. Top 3 third-party (independent expenditures) spenders

**Comment by ckingbailey** [comment]
Here's the new design:
![Screen Shot 2020-01-26 at 6.41.11 PM.png](https://images.zenhubusercontent.com/5c9031c88dcdbd6b61379151/72a1f861-b38e-4300-958d-0316e0405085)

**Comment by elinaru** [comment]
If anyone has any feedback on the mock-up, please feel free to add it as a comment to InVision -- https://invis.io/5VVJYRCRJTB

**Comment by ckingbailey** [comment]
1. Is easily solved with what's already in _data/totals.json
![Screen Shot 2020-01-29 at 8.19.00 PM.png](https://images.zenhubusercontent.com/5c9031c88dcdbd6b61379151/d06551bd-3405-4e97-9652-98e6ceb0eeb6)

**Comment by anlawyer** [comment]
Closed with: https://github.com/caciviclab/odca-jekyll/pull/348 and #212.
