### ISSUE TITLE
Ballot measure committees aren't showing expenditure data

### ISSUE THREAD

**Issue by anlawyer** [caciviclab/disclosure-backend-static#213]
According to @sfdoran, both ballot measure committees for Measure Q (Yes and No on Q) have expenditures that should be showing on the site, but they currently say "No expenditures have been reported by this committee". See screenshot below. 

![Screen Shot 2020-02-25 at 7.45.05 PM.png](https://images.zenhubusercontent.com/5dc09fc97b4f6300015900f4/05ba8558-8b1c-4c61-8fa0-d0fda978514a)

**Comment by ckingbailey** [comment]
This was resolved by a [backend PR](https://github.com/caciviclab/disclosure-backend-static/pulls?q=is%3Apr+is%3Aclosed), but I can't find which one

![Screen Shot 2020-02-25 at 10 38 06 PM](https://user-images.githubusercontent.com/20404311/75318541-83ff5280-581f-11ea-85d7-c03dac465534.png)

**Comment by anlawyer** [comment]
Hmm yea, not sure what magic @tdooner did to make it work, but it looks good now!

**Comment by anlawyer** [comment]
Oh wait I remember now, something had to be added to the spreadsheet to make it work. 👍

**Comment by tdooner** [comment]
Yep, that's it. Just had to rebuild.
