### ISSUE TITLE
Filter out $0 races from most expensive list

### ISSUE THREAD

**Issue by gauravmk** [caciviclab/disclosure-backend-static#224]
See https://github.com/caciviclab/disclosure-backend-static/pull/222#discussion_r401274670

For election overviews, we pull the 3 most expensive races but we should filter out any races that have a total of $0. See https://projects.invisionapp.com/d/main#/console/15245532/316959430/preview for the mocks for what those 3 most expensive races look like

**Comment by JoHeyJo** [comment]
Happy to tackle this one!

**Comment by JoHeyJo** [comment]
@mikeubell I can adjust the function `build_file('/_data/totals.json')…` in `process.rb` so that any “most_expensive_races” that equal 0 don’t get written into totals.json at all or do we prefer to have a record of that and filter from `totals.json` ?

**Comment by mikeubell** [comment]
Fixed via merge of #325
