### ISSUE TITLE
Calculate referendum supporting/opposing `total_contributions` value

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#23]
In the `referendums/:id/supporting` and  `referendums/:id/opposing` objects, there is a `total_contributions` value that is currently stubbed.

We should calculate that based on the 460 schedule A data combined with whatever independent expenditure forms we can find.

**Comment by adborden** [comment]
I think this was fixed by https://github.com/caciviclab/disclosure-backend-static/pull/36
cc @mikeubell

**Comment by tdooner** [comment]
We have this now!
