### ISSUE TITLE
Source data for "Where is the money coming from"

### ISSUE THREAD

**Issue by gauravmk** [caciviclab/disclosure-backend-static#230]
We need to provide the frontend with the data to power this section (aggregated at an election-level):

<img width="423" alt="Screen Shot 2020-03-31 at 9 07 39 PM" src="https://user-images.githubusercontent.com/16271389/78098761-cd9a0a80-7394-11ea-9f9d-d189fe476d8f.png">

**Comment by mikeubell** [comment]
The real data is fixed via #244
