### ISSUE TITLE
Endpoint for ballot measure contributors

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#25]
"It's like #20 but for ballot measures!"

Mock: https://cloud.githubusercontent.com/assets/6467815/18463189/0cc264b0-793d-11e6-8956-afc64f1c1f3d.png

For each committee that has a contribution to a ballot measure, we should return a list of _other_ things that committee has done. Look through the data: are these independent committees financing candidates? Or doing anything more than just supporting/opposing a single ballot measure? If not, we probably don't need to build this page.

Otherwise, we should create some object like `/committee/:id/supported_referendums` or something like that which returns that data in some format.

**Comment by sfdoran** [comment]
From what I've observed there is one committee contributing to multiple school board candidates & making independent expenditures on their behalf, that info is from the 24-hour late contribution & late i.e. reports. I haven't seen a committee supporting candidates & ballot measures yet, but it's possible.

**Comment by adborden** [comment]
I think this is done.
