### ISSUE TITLE
Search not returning all transactions for "bloomberg"

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/disclosure-backend-static#269]
Not sure if the problem is on the front end or the back end so I thought I'd check with @mikeubell first. 

On 9/11/2020 Michael Bloomberg made a $200,000 contribution to an Oakland PAC. Our search returns Bloomberg contributions for 2014, 2016 and 2018, but not 2020. He is in the spreadsheet as a major donor.

I'd like to figure this out quick, because I'd like him to be an example for the demo.

**Comment by mikeubell** [comment]
Bloomberg donated to Power2Familes which recently registered, but has not spent any money in this election.
We currently only include records for candidates and ballot measure committees and  for committees which have spent money in the campaign, either via independent expenditures or by donating to candidates.  We also include all records of contributions to those committees.  
I believe a committee based in Oakland has to register in Oakland even if they are not spending money for a current oakland election, true?  If so how do we tell if money given to that committee is in the current election or even planning to spend money on a local campaign?

**Comment by mikeubell** [comment]
We could put a column in committees: mark_active, which if set then we would force that committee into the index.
