### ISSUE TITLE
There are non-matching contributions / reciepts in Form 497

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#30]
Question for Suzanne: If everyone is in compliance, when a contribution over $1000 is made from a committee -> committee, we should see it twice in Form 497, right?

(We would see it once on F497 Page 1 filed by the contributing committee, and once on F497 Page 2 filed by the receiving committee.)

But there are instances right now where a contribution is not reported by both committees. For instance:

` Oakland Police Officer's Association - Political Action Committee`
gave $1400 to Filer ID 1387192 ("Viola Gonzales for City Council 2016") but the corresponding receipt by her committee does not appear.

Is this a known filing discrepancy to the PEC?

**Comment by sfdoran** [comment]
Yes, that's right. I've contacted all of these candidates, so you should be seeing their 497s soon - except one candidate who returned the check because she did not want to accept that committee's support. We should make sure that contribution is not credited to her.
