### ISSUE TITLE
Include Form 496 data in ballot measure candidate / opposition totals

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#34]
This form lists independent expenditures in support or opposition to a ballot measure or candidate.

Currently there is not much here except for some school advocacy, but this sheet is gonna fill up soon.

- [ ] ballot measure supporting / opposing calculator
- [ ] ? candidate opposing calculator ( 🌟 NEW!)

Matching up to candidate is going to be tricky since the form doesn't include the candidate's recipient committee id :(. For any ballot measures without a Bal_Num we can use, add to the mapping in `models/oakland_referendum.rb`.

**Comment by mikeubell** [comment]
Should we have a new field for IE rather than lump it into candidate/measure supporting/opposing totals?
