### ISSUE TITLE
Missing contributions?

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend-static#46]
Going through all the contributions we have in Oakland, I was expecting something around 1400 (before the 9/29 filing deadline) But only seeing 679.
```
$ ls -1 build/committee/ | while read fppc; do curl "https://disclosure-backend-static.tdooner.com/committee/$fppc/contributions" | jq '.[]'; done  |  jq --slurp '. | length'
679
```

cc @KyleW

**Comment by mikeubell** [comment]
That is what data is in the database for the candidates we are tracking:
SELECT count(*) from 
"efile_COAK_2016_A-Contributions"
WHERE "Filer_ID" IN ('1294190',
'1307016',
'1331137',
'1342695',
'1344506',
'1345259',
'1364564',
'1372459',
'1379618',
'1380387',
'1381041',
'1385180',
'1385949',
'1386145d',
'1387983',
'892160',
'983545',
'S10088');
disclosure-backend=# \g
 count 
-------
   628

**Comment by adborden** [comment]
This comment refers to @tdooner's comment https://github.com/caciviclab/disclosure-backend-static/issues/20#issuecomment-247823153 about having 1447 contributions in the entire data set (pre-9/29). I had just assumed that we would be seeing that number of contributions somewhere in the API, maybe that was wrong, or we're not pulling in all committees just yet?

**Comment by mikeubell** [comment]
There are contributions to things like Office Holder accounts.  I also don't think we are tracking school board election candidates.

**Comment by tdooner** [comment]
> 1447 contributions in the entire data set (pre-9/29)
Yeah, that was a simple `SELECT COUNT(*)` which included contributions to committees that we are not showing.

>  I also don't think we are tracking school board election candidates.
We are!

I'm gonna close this unless someone can point to a specific transaction that is missing.
