### ISSUE TITLE
Primarily formed ballot measure committees not appearing on referendum list of supporting/opposing committees

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend-static#47]
@tdooner @mikeubell, @sfdoran's staff brought this up when combing over the site this week. It looks like there are committees that aren't showing up as supporting/opposing ballot measures. Unfortunately, this means the data we're showing is misleading, so we'd like to fix this ASAP.

In most of the these cases, these are Ballot Measure Committees (BMC) formed primarily to support or defeat a specific ballot measure. In this case, the committee usually does not specify their expenditures were in support or opposing a ballot measure on Schedule D, they just leave it blank. In that case, we should be attributing those expenditures to the ballot measure they were primarily formed for.

For primarily formed ballot measure committees, we have the measure number they are in support/opposing in the committee spreadsheet, although I am not sure if we also need the support/oppose value, hope one of you can comment on this.

- [Measure KK supporting committee not showing](http://www.opendisclosure.io/#!/city/2/oakland/2016/referendum/4/infrastructure-and-housing-bonds/supporting). Data on supporting committee in spreadsheet: Invest in Oakland's Infrastructure and Affordable Housing -- Yes on KK, a Coalition of Business, Community Leaders and Oakland Residents, FPPC#1387983
- [Measure KK supporting committee showing “Causa Justa”Justa](http://www.opendisclosure.io/#!/city/2/oakland/2016/referendum/4/infrastructure-and-housing-bonds/supporting). This committee is primarily formed to support JJ. Spreadsheet addition had incorrect info – people should check the designations correspond with committee sheet
- [Measure JJ shows only one committee supporting: Committee to Protect Oakland Renters](http://www.opendisclosure.io/#!/city/2/oakland/2016/referendum/3/just-cause-for-eviction-and-rent-adjustment/supporting). Should show 2 committees: Committee to Protect Oakland Renters and Causa Justa – see above.
- [Measure LL shows no supporting committees](http://www.opendisclosure.io/#!/city/2/oakland/2016/referendum/5/police-commission). Should show Coalition for Police Accountability Yes on LL, FPPC#1386145 (no financial data yet, but Form 410 filed showing this is the supporting committee) – info is in the spreadsheet linking this committee to measure LL

**Comment by mikeubell** [comment]
Seems like we should add a support/opposed column to the committees tab of the Oakland Candidates spreadsheet.  We can then join this with schedule E to get what we need.

**Comment by mikeubell** [comment]
@adborden I cannot find a case where a committee (that is in our committees sheet) has not specified S/O for an expense in either Schedule D or E.  I could see how it might happen but I'd like to know what case the staff came up with.

**Comment by adborden** [comment]
@mikeubell can you check the above examples again? Not sure if there's new data now, or something was added to the spreadsheet, but I'm seeing 13 rows for the Yes on LL committee, filer id 1386145. Sure enough, they don't show up on the LL ballot measure page as supporters and they don't have any ballot information in their schedule E.

```
disclosure-backend=# select "Filer_ID", "Bal_Name", "Bal_Num", "Sup_Opp_Cd", "Amount" from "efile_COAK_2016_E-Expenditure" where "Filer_ID" = '1386145';
 Filer_ID | Bal_Name | Bal_Num | Sup_Opp_Cd | Amount
----------+----------+---------+------------+--------
 1386145  |          |         |            |    200
 1386145  |          |         |            |    850
 1386145  |          |         |            |   1500
 1386145  |          |         |            |    250
 1386145  |          |         |            |    350
 1386145  |          |         |            |  240.1
 1386145  |          |         |            | 239.41
 1386145  |          |         |            |     50
 1386145  |          |         |            |     35
 1386145  |          |         |            | 374.22
 1386145  |          |         |            | 264.58
 1386145  |          |         |            |  38.33
 1386145  |          |         |            |    565
(13 rows)
```

**Comment by mikeubell** [comment]
Ah... this data is new since I looked last.  As I said I thought this was possible but did not see it in the data.  Now I can see it.
