### ISSUE TITLE
Data for the city-level election

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend-static#58]
What work is needed to get the data for the city-level election page?
[Invision desktop](https://projects.invisionapp.com/share/TK8O67TEZ#/screens/190014309)
![screenshot from 2016-10-07 19-38-10](https://cloud.githubusercontent.com/assets/509703/19209709/a0ae35be-8cc5-11e6-9901-253f22635f2f.png)

**Comment by adborden** [comment]
@tdooner is this something we want to tackle for v2?

**Comment by adborden** [comment]
This is an [updated mock](https://projects.invisionapp.com/share/TK8O67TEZ#/screens/190014309)

![screencapture-projects-invisionapp-share-tk8o67tez-2018-05-15-19_44_11](https://user-images.githubusercontent.com/509703/40093746-6439ce6a-5878-11e8-99e7-06008718c1bb.png)

**Comment by mikeubell** [comment]
I believe this has been addressed.
