### ISSUE TITLE
(Excel Spreadsheet) Candidate photo colum cleanup

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#7]
Cleanup the spreadsheet https://docs.google.com/spreadsheets/d/1272oaLyQhKwQa6RicA5tBso6wFruum-mgrNm3O3VogI/edit#gid=0

so that there is a column with the photo URLs.

**Comment by elinaru** [comment]
Photos can be found here: https://drive.google.com/drive/folders/0B_mJPkm423eVdFJQMXJLTjZKcmc

**Comment by adborden** [comment]
Thanks Elina! This is done, I've uploaded the photos to S3 and updated the spreadsheet. They're already in the API.
