### ISSUE TITLE
Ballot measure contributions calculation looks off

### ISSUE THREAD

**Issue by mikeubell** [caciviclab/disclosure-backend-static#73]
This was originally filed on the front end as #251.

filing shows $10,745,941.73 total contributions - site shows $13,839,546.

http://www.opendisclosure.io/#!/city/2/oakland/2016/referendum/1/sugar-sweetened-beveragetax

**Comment by adborden** [comment]
Backlink https://github.com/caciviclab/disclosure-frontend/issues/251
