### ISSUE TITLE
Investigate heroku add-ons for search feature

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#75]
Under "search" on here:
https://elements.heroku.com/addons

Which addons can we index all our contributors / recipients with?
Which are cheap?
Maybe worth testing one out and seeing how it works.

**Comment by mikeubell** [comment]
Algolia Realtime Search seems to have everything we need: 
indexing on specific columns
Typeahead search
Integrates with Javascript and Ruby

The client can talk directly to the Algolia server so we need no back end changes other than to get the data indexed.

**Comment by tdooner** [comment]
I agree - its free tier seems like it will do the trick for us. At some point I'll spin up a free trial and see what it looks like from the inside -- and I'd say for you to feel free to do the same if you get some time.

**Comment by mikeubell** [comment]
Swiftype seems to have similar features to Aloglia but seems less database centric and less integrated with back end code.  It seems that you would have to code your updates to the search engine directly rather than having integration with ruby models.

**Comment by mikeubell** [comment]
Elastic Search has features similar to Algolia. 
Integrated with Ruby
Indexing on specific columns
Has a "suggestion" api.

**Comment by tdooner** [comment]
We've got Algolia now, closing this out.
