### ISSUE TITLE
Prototype elasticsearch indexing process during the build

### ISSUE THREAD

**Issue by tdooner** [caciviclab/disclosure-backend-static#76]
It's likely that whichever Heroku add-on we select will be elasticsearch or similar to it.

Let's prototype an elasticsearch indexing step in the pipeline which has the following stuff:
* contributor names and IDs
* recipient names and IDs

This is just for the backend, it is okay to be able to query this via the command line only.

https://docs.google.com/document/d/1fu0GMbicaERV_7R0aoLBw1ST-yFM1P3K_8mqhDTOcGs/edit#heading=h.chyrjd53oksh

**Comment by adborden** [comment]
I think this is done, anything left to do here? Maybe write up the learnings?

**Comment by mikeubell** [comment]
We are using Algolia Search.
