### ISSUE TITLE
Create ballot for San Francisco November 6, 2018 election

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend-static#85]
We need folks to seek out all candidate and referendum info for San Francisco in the November 6, 2018 election. Info we need is:

### Candidate
- FPPC#
- Committee Name
- Candidate
- Aliases
- Office
- Incumbent
- Accepted expenditure ceiling
- Website
- Twitter
- Party Affiliation
- Occupation
- Bio
- Photo
- VotersEdge
- Internal Notes

### Referendum

- Measure number
- Short Title
- Full Title
- Summary
- VotersEdge
- Internal notes

**Comment by adborden** [comment]
This is more of a front end task because it means updating the spreadsheet and odca-jekyll.

**Comment by r-i-c-h** [comment]
I would think this is done

**Comment by adborden** [comment]
On Tue, 2018-12-11 at 20:56 -0800, Rich Werden <notifications@github.com> wrote:
> I would think this is done

It is not. There is a lot of information missing on the SF ballot.
https://www.opendisclosure.io/election/sf/2018-11-06/

--
Aaron D Borden
Human and Hacker
