### ISSUE TITLE
"Yes on G1, Sponsored by Go Public Schools Advocates" has broken link

### ISSUE THREAD

**Issue by adborden** [caciviclab/disclosure-backend-static#87]
Looking at the [supporters of G1](http://www.opendisclosure.io/#!/city/2/oakland/2016/referendum/6/oakland-school-bond/supporting), Yes on G1, Sponsored by Go Public Schools Advocates has no committee id, so the link is broken. I see a filer id in this [spreadsheet](https://docs.google.com/spreadsheets/d/1272oaLyQhKwQa6RicA5tBso6wFruum-mgrNm3O3VogI/edit#gid=387884938), so I'm not sure what's up.

**Comment by sfdoran** [comment]
The committee id for Yes on G1 was wrong. I updated the spreadsheet. I found two local ballot measure committees supporting this measure:

Friends of Oakland Public Schools, 960997
YES ON G1, SPONSORED BY GO PUBLIC SCHOOLS ADVOCATES, 1391632

I also added the sponsoring state committee to the spreadsheet just in case.

**Comment by adborden** [comment]
This is fixed.
